/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fsm.alienes_gurel_2121221032_bp2_p2;

import java.util.ArrayList;
import javax.swing.ButtonModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alien
 */
public class AkademisyenDersIcerik extends javax.swing.JFrame {

    Main main = new Main();
    DefaultTableModel tbl_dersler_model;
    DefaultTableModel tbl_dersler_model2;
    DefaultTableModel tbl_dersiAlanlar_model;
    DefaultTableModel tbl_kullanicilar_model;
    JFrame parentFrame;
    Kullanici kullanici;

    /**
     * Creates new form AkademistDersIcerik
     */
    public AkademisyenDersIcerik(Kullanici kullanici) {
        initComponents();
        this.setTitle("AKADEMISYEN");
        this.kullanici = kullanici;
        menu_kullanici.setText(kullanici.ad_soyad);
        tbl_dersler_model = new DefaultTableModel();
        tbl_dersler_model.setColumnIdentifiers(new Object[]{"DERS ID", "DERS ADI"});
        tbl_dersler.setModel(tbl_dersler_model);
        tbl_dersler_model2 = new DefaultTableModel();
        tbl_dersler_model2.setColumnIdentifiers(new Object[]{"DERS ID", "DERS ADI"});
        tbl_dersler2.setModel(tbl_dersler_model2);
        tbl_dersiAlanlar_model = new DefaultTableModel();
        tbl_dersiAlanlar_model.setColumnIdentifiers(new Object[]{"OGRENCI ID", "OGRENCI ADI"});
        tbl_dersiAlanlar.setModel(tbl_dersiAlanlar_model);
        tbl_kullanicilar_model = new DefaultTableModel();
        tbl_kullanicilar_model.setColumnIdentifiers(new Object[]{"ID", "ADI-SOYADI", "KULLANICI TURU", "DERS AKTS"});
        tbl_kullanicilar.setModel(tbl_kullanicilar_model);
        btn_icerigiKaydet.setEnabled(false);
        SetCourseToTable();
        SetKullaniciToTable();
        DuyuruDisiniKapa(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_dersler = new javax.swing.JTable();
        txt_tumDersArama = new javax.swing.JTextField();
        btn_tumDersArama = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_dersId = new javax.swing.JTextField();
        txt_dersAdi = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txta_dersIcerigi = new javax.swing.JTextArea();
        btn_yeniDersEkle = new javax.swing.JButton();
        btn_dersiGuncelle = new javax.swing.JButton();
        btn_dersiSil = new javax.swing.JButton();
        btn_temizle = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txt_aktsGuncelle = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_dersiAlanlar = new javax.swing.JTable();
        txt_ogrenciBul = new javax.swing.JTextField();
        btn_derstenCikar = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_dersler2 = new javax.swing.JTable();
        txt_tumDersArama2 = new javax.swing.JTextField();
        btn_tumDersArama2 = new javax.swing.JButton();
        cmbx_haftaSec = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        rbtn_vize = new javax.swing.JRadioButton();
        rbtn_final = new javax.swing.JRadioButton();
        rbtn_quiz = new javax.swing.JRadioButton();
        rbtn_video = new javax.swing.JRadioButton();
        rbtn_pdf = new javax.swing.JRadioButton();
        rbtn_odev = new javax.swing.JRadioButton();
        btn_icerigiKaydet = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        lbl_seciliDers = new javax.swing.JLabel();
        btn_secimiTemizle = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        lbl_seciliHafta = new javax.swing.JLabel();
        btn_kontrol = new javax.swing.JButton();
        btn_icerikGuncelle = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_kullanici_id = new javax.swing.JTextField();
        txt_guncelleAdSoyad1 = new javax.swing.JTextField();
        txt_guncelleEmail1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_guncelleParola1 = new javax.swing.JTextField();
        txt_guncelleNumara1 = new javax.swing.JTextField();
        lbl_ogrenciNumarasi = new javax.swing.JLabel();
        btn_bilgileriGuncelle1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txt_guncelleKullaniciTuru1 = new javax.swing.JTextField();
        btn_kullaniciSil = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_aldigiAkts = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_kullanicilar = new javax.swing.JTable();
        txt_ogrenciArama = new javax.swing.JTextField();
        btn_ogrenciArama = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_akademisyenId = new javax.swing.JTextField();
        txt_guncelleAdSoyad = new javax.swing.JTextField();
        txt_guncelleEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_guncelleParola = new javax.swing.JTextField();
        btn_bilgileriGuncelle = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_kullanici = new javax.swing.JMenu();
        menuItem_cikis = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 102, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(51, 0, 0));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DERSLERI GORUNTULE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_dersler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DERS ID", "DERS ADI"
            }
        ));
        tbl_dersler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_derslerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_dersler);

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 380, 400));
        jPanel8.add(txt_tumDersArama, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 23, 225, -1));

        btn_tumDersArama.setText("DERSLERI ARAMA");
        btn_tumDersArama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tumDersAramaActionPerformed(evt);
            }
        });
        jPanel8.add(btn_tumDersArama, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 23, 143, -1));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 470));

        jPanel9.setBackground(new java.awt.Color(51, 0, 0));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DERS BILGILERI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DERS ADI");
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DERS ID");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 121, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DERS BILGISI");
        jPanel9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 121, 79, -1));
        jPanel9.add(txt_dersId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 150, -1));
        jPanel9.add(txt_dersAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 150, -1));

        txta_dersIcerigi.setColumns(20);
        txta_dersIcerigi.setRows(5);
        jScrollPane3.setViewportView(txta_dersIcerigi);

        jPanel9.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 250, 180));

        btn_yeniDersEkle.setText("YENI DERS EKLE");
        btn_yeniDersEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_yeniDersEkleActionPerformed(evt);
            }
        });
        jPanel9.add(btn_yeniDersEkle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 130, 46));

        btn_dersiGuncelle.setText("DERSI GUNCELLE");
        btn_dersiGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dersiGuncelleActionPerformed(evt);
            }
        });
        jPanel9.add(btn_dersiGuncelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 130, 46));

        btn_dersiSil.setText("DERSI SIL");
        btn_dersiSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dersiSilActionPerformed(evt);
            }
        });
        jPanel9.add(btn_dersiSil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 250, 40));

        btn_temizle.setText("TEMIZLE");
        btn_temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_temizleActionPerformed(evt);
            }
        });
        jPanel9.add(btn_temizle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 250, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DERS AKTS");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        jPanel9.add(txt_aktsGuncelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 150, -1));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 270, 470));

        jPanel10.setBackground(new java.awt.Color(102, 0, 0));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DERSI ALAN OGRENCILER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_dersiAlanlar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OGRENCI ID", "OGRENCI ADI"
            }
        ));
        tbl_dersiAlanlar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_dersiAlanlarMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_dersiAlanlar);

        jPanel10.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 270, 330));
        jPanel10.add(txt_ogrenciBul, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 260, -1));

        btn_derstenCikar.setBackground(new java.awt.Color(102, 0, 0));
        btn_derstenCikar.setForeground(new java.awt.Color(255, 255, 255));
        btn_derstenCikar.setText("DERSTEN CIKAR");
        btn_derstenCikar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_derstenCikarActionPerformed(evt);
            }
        });
        jPanel10.add(btn_derstenCikar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 270, 30));

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 290, 470));

        jTabbedPane1.addTab("DERS ISLEMLERI", jPanel2);

        jPanel11.setBackground(new java.awt.Color(51, 0, 0));

        jPanel12.setBackground(new java.awt.Color(51, 0, 0));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DERSLERI GORUNTULE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_dersler2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DERS ID", "DERS ADI"
            }
        ));
        tbl_dersler2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_dersler2MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbl_dersler2);

        jPanel12.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 380, 400));
        jPanel12.add(txt_tumDersArama2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 23, 225, -1));

        btn_tumDersArama2.setText("DERSLERI ARAMA");
        btn_tumDersArama2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tumDersArama2ActionPerformed(evt);
            }
        });
        jPanel12.add(btn_tumDersArama2, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 23, 143, -1));

        cmbx_haftaSec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Icerik eklemek istediginiz haftayi seciniz", "Hafta 1", "Hafta 2", "Hafta 3", "Hafta 4", "Hafta 5", "Hafta 6", "Hafta 7", "Hafta 8", "Hafta 9", "Hafta 10", "Hafta 11", "Hafta 12", "Hafta 13", "Hafta 14", "Hafta 15" }));
        cmbx_haftaSec.setEnabled(false);
        cmbx_haftaSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbx_haftaSecActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("ICERIK EKLE");

        buttonGroup2.add(rbtn_vize);
        rbtn_vize.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbtn_vize.setForeground(new java.awt.Color(255, 255, 255));
        rbtn_vize.setText("VIZE SINAVI");

        buttonGroup2.add(rbtn_final);
        rbtn_final.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbtn_final.setForeground(new java.awt.Color(255, 255, 255));
        rbtn_final.setText("FINAL SINAVI");
        rbtn_final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_finalActionPerformed(evt);
            }
        });

        rbtn_quiz.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbtn_quiz.setForeground(new java.awt.Color(255, 255, 255));
        rbtn_quiz.setText("QUIZ");

        rbtn_video.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbtn_video.setForeground(new java.awt.Color(255, 255, 255));
        rbtn_video.setText("DERS KAYIT VIDEOSU");

        rbtn_pdf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbtn_pdf.setForeground(new java.awt.Color(255, 255, 255));
        rbtn_pdf.setText("DERS ICERIK PDF");

        rbtn_odev.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbtn_odev.setForeground(new java.awt.Color(255, 255, 255));
        rbtn_odev.setText("ODEV");

        btn_icerigiKaydet.setText("ICERIGI KAYDET");
        btn_icerigiKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_icerigiKaydetActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("SECILI DERS :");

        lbl_seciliDers.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_seciliDers.setForeground(new java.awt.Color(255, 255, 255));

        btn_secimiTemizle.setText("SECIMI TEMIZLE");
        btn_secimiTemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_secimiTemizleActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("SECILI HAFTA :");

        lbl_seciliHafta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_seciliHafta.setForeground(new java.awt.Color(255, 255, 255));

        btn_kontrol.setText("KONTROL");
        btn_kontrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kontrolActionPerformed(evt);
            }
        });

        btn_icerikGuncelle.setText("ICERIGI GUNCELLE");
        btn_icerikGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_icerikGuncelleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbx_haftaSec, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_secimiTemizle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btn_icerigiKaydet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbtn_pdf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                    .addComponent(rbtn_vize, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbtn_quiz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtn_final, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(rbtn_video, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                            .addComponent(rbtn_odev, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(btn_icerikGuncelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_kontrol))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_seciliDers, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_seciliHafta, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 31, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 74, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_seciliHafta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lbl_seciliDers, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbx_haftaSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_kontrol))
                .addGap(32, 32, 32)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_vize)
                    .addComponent(rbtn_final))
                .addGap(57, 57, 57)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_quiz)
                    .addComponent(rbtn_odev))
                .addGap(57, 57, 57)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_pdf)
                    .addComponent(rbtn_video))
                .addGap(40, 40, 40)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_icerigiKaydet, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btn_icerikGuncelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_secimiTemizle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ICERIK EKLE", jPanel11);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jPanel5.setBackground(new java.awt.Color(0, 0, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "KULLANICI BILGILERI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jPanel7.setBackground(new java.awt.Color(0, 51, 51));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("KULLANICI ID");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("AD - SOYAD");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("E-MAIL");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("PAROLA");

        lbl_ogrenciNumarasi.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ogrenciNumarasi.setText("OGRENCI NUMARASI");

        btn_bilgileriGuncelle1.setBackground(new java.awt.Color(51, 0, 51));
        btn_bilgileriGuncelle1.setForeground(new java.awt.Color(255, 255, 255));
        btn_bilgileriGuncelle1.setText("BILGILERI GUNCELLE");
        btn_bilgileriGuncelle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bilgileriGuncelle1ActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("KULLANICI TURU");

        btn_kullaniciSil.setBackground(new java.awt.Color(51, 0, 0));
        btn_kullaniciSil.setForeground(new java.awt.Color(255, 255, 255));
        btn_kullaniciSil.setText("KULLANICI SIL");
        btn_kullaniciSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kullaniciSilActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ALDIGI AKTS");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_bilgileriGuncelle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_kullaniciSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_guncelleParola1)
                                    .addComponent(txt_guncelleKullaniciTuru1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txt_aldigiAkts, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_guncelleAdSoyad1)
                            .addComponent(txt_guncelleEmail1)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(66, 66, 66)
                        .addComponent(txt_kullanici_id))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(lbl_ogrenciNumarasi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_guncelleNumara1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_kullanici_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_guncelleAdSoyad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_guncelleEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_guncelleParola1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ogrenciNumarasi)
                    .addComponent(txt_guncelleNumara1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_guncelleKullaniciTuru1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_aldigiAkts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btn_bilgileriGuncelle1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_kullaniciSil, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane2.setRightComponent(jPanel5);

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "KULLANICI BUL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        tbl_kullanicilar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ADI-SOYADI", "KULLANICI TURU", "ALDIGI AKTS"
            }
        ));
        tbl_kullanicilar.setMinimumSize(new java.awt.Dimension(0, 0));
        tbl_kullanicilar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_kullanicilarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_kullanicilar);

        btn_ogrenciArama.setText("OGRENCI ARAMA");
        btn_ogrenciArama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ogrenciAramaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_ogrenciArama, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_ogrenciArama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ogrenciArama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ogrenciArama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane2.setLeftComponent(jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jSplitPane2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("KULLANICI ISLEMLERI", jPanel1);

        jPanel4.setBackground(new java.awt.Color(51, 51, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AKADEMISYEN BILGILERINI GUNCELLE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel6.setBackground(new java.awt.Color(0, 51, 51));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("AKADEMISYEN ID");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("AD - SOYAD");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("E-MAIL");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PAROLA");

        btn_bilgileriGuncelle.setBackground(new java.awt.Color(51, 51, 0));
        btn_bilgileriGuncelle.setForeground(new java.awt.Color(255, 255, 255));
        btn_bilgileriGuncelle.setText("BILGILERIMI GUNCELLE");
        btn_bilgileriGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bilgileriGuncelleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_akademisyenId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_guncelleEmail)
                                .addComponent(txt_guncelleAdSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_guncelleParola, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_bilgileriGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_akademisyenId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_guncelleAdSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_guncelleEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_guncelleParola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(63, 63, 63)
                .addComponent(btn_bilgileriGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = -23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 290, 35, 291);
        jPanel4.add(jPanel6, gridBagConstraints);

        jTabbedPane1.addTab("AKADEMISYEN BILGILERINI DUZENLE", jPanel4);

        getContentPane().add(jTabbedPane1);

        menu_kullanici.setText("KULLANICI");

        menuItem_cikis.setText("CIKIS");
        menuItem_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_cikisActionPerformed(evt);
            }
        });
        menu_kullanici.add(menuItem_cikis);

        jMenuBar1.add(menu_kullanici);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void SetKullaniciToTable() {
        ArrayList<Kullanici> kullanicilar = DB_Ders_Icerik_Takibi.OgrencileriGetir();
        tbl_kullanicilar_model.setRowCount(0);
        for (Kullanici kul : kullanicilar) {
            if (kul.kullanici_turu.equals("OGRENCI")) {
                tbl_kullanicilar_model.addRow(new Object[]{kul.id, kul.ad_soyad, kul.kullanici_turu, kul.kullanici_akts});
            }
        }
    }

    private void SetCourseToTable() {
        ArrayList<Ders> dersler = DB_Ders_Icerik_Takibi.DersleriGetir();
        tbl_dersler_model.setRowCount(0);
        for (Ders ders : dersler) {
            tbl_dersler_model.addRow(new Object[]{ders.id, ders.ders_adi, ders.ders_akts});
        }
    }
    private void menuItem_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_cikisActionPerformed
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuItem_cikisActionPerformed

    private void btn_bilgileriGuncelle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bilgileriGuncelle1ActionPerformed
        Kullanici k1 = new Kullanici();
        if (kullanici != null) {
            k1.id = Integer.parseInt(txt_kullanici_id.getText());
            txt_kullanici_id.setEnabled(false);
            k1.ad_soyad = txt_guncelleAdSoyad1.getText();
            k1.email = txt_guncelleEmail1.getText();
            k1.parola = txt_guncelleParola1.getText();
            k1.ogrenci_numarasi = txt_guncelleNumara1.getText();
            k1.kullanici_akts = Integer.parseInt(txt_aldigiAkts.getText());
            DB_Ders_Icerik_Takibi.UpdateKullanici(k1);
            if (DB_Ders_Icerik_Takibi.UpdateKullanici(k1)) {
                txt_kullanici_id.setText("");
                txt_guncelleAdSoyad1.setText("");
                txt_guncelleEmail1.setText("");
                txt_guncelleParola1.setText("");
                txt_guncelleNumara1.setText("");
                txt_guncelleKullaniciTuru1.setText("");
                txt_aldigiAkts.setText("");
                JOptionPane.showMessageDialog(parentFrame, "Basarili");
            } else {
                JOptionPane.showMessageDialog(parentFrame, "Basarisiz");
            }
        }
    }//GEN-LAST:event_btn_bilgileriGuncelle1ActionPerformed
    public void DuyuruDisiniKapa(boolean kapat) {
        rbtn_final.setEnabled(kapat);
        rbtn_vize.setEnabled(kapat);
        rbtn_quiz.setEnabled(kapat);
        rbtn_odev.setEnabled(kapat);
        rbtn_video.setEnabled(kapat);
        rbtn_pdf.setEnabled(kapat);

    }
    private void btn_yeniDersEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_yeniDersEkleActionPerformed
        Ders d = new Ders();
        txt_dersId.setEnabled(false);
        d.ders_adi = txt_dersAdi.getText();
        d.icerik = txta_dersIcerigi.getText();
        d.ders_akts = Integer.parseInt(txt_aktsGuncelle.getText());
        if (!txt_dersAdi.getText().isEmpty() || !txt_aktsGuncelle.getText().isEmpty()
                || !txta_dersIcerigi.getText().isEmpty() || !txt_aktsGuncelle.getText().isEmpty()) {
            if (DB_Ders_Icerik_Takibi.AddDers(d) && DB_Ders_Icerik_Takibi.UpdateDersDB(d)) {
                JOptionPane.showMessageDialog(parentFrame, "Basarili");
            } else {
                JOptionPane.showMessageDialog(parentFrame, "Basarisiz");
            }
        } else {
            JOptionPane.showMessageDialog(parentFrame, "Basarisiz");
        }
    }//GEN-LAST:event_btn_yeniDersEkleActionPerformed

    private void btn_tumDersAramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tumDersAramaActionPerformed
        txt_ogrenciBul.setText("");
        btn_yeniDersEkle.setEnabled(true);
        btn_dersiSil.setEnabled(true);
        String search = this.txt_tumDersArama.getText();
        tbl_dersler_model.setRowCount(0);
        ArrayList<Ders> dersList = DB_Ders_Icerik_Takibi.aramaTumDers(search);
        for (Ders d1 : dersList) {
            tbl_dersler_model.addRow(new Object[]{d1.id, d1.ders_adi});
        }
        txt_dersId.setText("");
        txt_dersAdi.setText("");
        txta_dersIcerigi.setText("");
        txt_aktsGuncelle.setText("");
        tbl_dersiAlanlar_model.setRowCount(0);
    }//GEN-LAST:event_btn_tumDersAramaActionPerformed

    private void tbl_derslerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_derslerMouseClicked
        btn_yeniDersEkle.setEnabled(false);
        btn_dersiSil.setEnabled(true);
        txt_ogrenciBul.setText(tbl_dersler_model.getValueAt(tbl_dersler.getSelectedRow(), 1).toString());
        txt_ogrenciBul.setEnabled(false);
        int id = (int) tbl_dersler_model.getValueAt(tbl_dersler.getSelectedRow(), 0);
        Ders d = DB_Ders_Icerik_Takibi.searchDersById(id);
        if (d != null) {
            txt_dersId.setText(d.id + "");
            txt_dersId.setEnabled(false);
            txt_dersAdi.setText(d.ders_adi);
            txta_dersIcerigi.setText(d.icerik);
            txt_aktsGuncelle.setText(d.ders_akts + "");
        }
        if (tbl_dersler.getSelectedRow() < 0) {
            return;
        }
        int search_id = (int) tbl_dersler_model.getValueAt(tbl_dersler.getSelectedRow(), 0);
        tbl_dersiAlanlar_model.setRowCount(0);
        ArrayList<Kullanici> kullaniciList = DB_Ders_Icerik_Takibi.aramaDersAlanlarById(search_id);
        for (Kullanici k2 : kullaniciList) {
            tbl_dersiAlanlar_model.addRow(new Object[]{k2.id, k2.ad_soyad});
        }
    }//GEN-LAST:event_tbl_derslerMouseClicked

    private void btn_dersiGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dersiGuncelleActionPerformed
        Ders d1 = new Ders();
        if (d1 != null) {
            d1.id = Integer.parseInt(txt_dersId.getText());
            txt_akademisyenId.setEnabled(false);
            d1.ders_adi = txt_dersAdi.getText();
            d1.icerik = txta_dersIcerigi.getText();
            d1.ders_akts = Integer.parseInt(txt_aktsGuncelle.getText());
            DB_Ders_Icerik_Takibi.UpdateDers(d1);
            DB_Ders_Icerik_Takibi.UpdateDersDB(d1);
        }
        if (DB_Ders_Icerik_Takibi.UpdateDers(d1)) {
            JOptionPane.showMessageDialog(parentFrame, "Basarili");
        } else {
            JOptionPane.showMessageDialog(parentFrame, "Basarisiz");
        }
    }//GEN-LAST:event_btn_dersiGuncelleActionPerformed

    private void btn_temizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_temizleActionPerformed
        btn_yeniDersEkle.setEnabled(true);
        btn_dersiSil.setEnabled(false);
        txt_dersId.setText("");
        txt_dersId.setEnabled(false);
        txt_dersAdi.setText("");
        txta_dersIcerigi.setText("");
        txt_aktsGuncelle.setText("");
        JOptionPane.showMessageDialog(parentFrame, "Temizlendi");
    }//GEN-LAST:event_btn_temizleActionPerformed

    private void btn_dersiSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dersiSilActionPerformed
        if (tbl_dersler.getSelectedRow() < 0) {
            return;
        }
        txt_dersId.setEnabled(false);
        String ders_adi = txt_dersAdi.getText();
        String ders_icerigi = txta_dersIcerigi.getText();
        DB_Ders_Icerik_Takibi.DeleteDers(ders_adi, ders_icerigi);
        if (DB_Ders_Icerik_Takibi.DeleteDers(ders_adi, ders_icerigi)) {
            JOptionPane.showMessageDialog(parentFrame, "Basarili");
        } else {
            JOptionPane.showMessageDialog(parentFrame, "Basarisiz");
        }
    }//GEN-LAST:event_btn_dersiSilActionPerformed

    private void tbl_dersiAlanlarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dersiAlanlarMouseClicked
        if (tbl_dersler.getSelectedRow() < 0) {
            return;
        }
        int id = (int) tbl_dersiAlanlar_model.getValueAt(tbl_dersiAlanlar.getSelectedRow(), 0);
        Kullanici k = DB_Ders_Icerik_Takibi.searchOgrenciById(id);
    }//GEN-LAST:event_tbl_dersiAlanlarMouseClicked

    private void btn_derstenCikarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_derstenCikarActionPerformed
//        if (tbl_dersiAlanlar.getSelectedRow() < 0) {
//            return;
//        }
//        int id_ogrenci = Integer.parseInt(tbl_dersiAlanlar_model.getValueAt(tbl_dersiAlanlar.getSelectedRow(), 0).toString());
//        int id_ders = Integer.parseInt(tbl_dersler_model.getValueAt(tbl_dersiAlanlar.getSelectedRow(), 0).toString());
//        if (DB_Ders_Icerik_Takibi.DerstenCikar(id_ogrenci, id_ders)) {
//            JOptionPane.showMessageDialog(parentFrame, "Basarili");
//        } else {
//            JOptionPane.showMessageDialog(parentFrame, "Basarisiz");
//        }
        if (tbl_dersiAlanlar.getSelectedRow() < 0) {
            return;
        }
        int id_ders = Integer.parseInt(tbl_dersler_model.getValueAt(tbl_dersler.getSelectedRow(), 0).toString());
        int id_ogrenci = Integer.parseInt(tbl_dersiAlanlar_model.getValueAt(tbl_dersiAlanlar.getSelectedRow(), 0).toString());
        if (DB_Ders_Icerik_Takibi.DerstenCikar(id_ogrenci, id_ders)) {
            JOptionPane.showMessageDialog(parentFrame, "Basarili");
        } else {
            JOptionPane.showMessageDialog(parentFrame, "Basarisiz");
        }
    }//GEN-LAST:event_btn_derstenCikarActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        if (kullanici != null) {
            txt_akademisyenId.setText(kullanici.id + "");
            txt_akademisyenId.setEnabled(false);
            txt_guncelleAdSoyad.setText(kullanici.ad_soyad + "");
            txt_guncelleEmail.setText(kullanici.email + "");
            txt_guncelleParola.setText(kullanici.parola + "");
        }
        btn_icerigiKaydet.setEnabled(false);
        btn_icerikGuncelle.setEnabled(false);
        btn_secimiTemizle.setEnabled(false);
        btn_kontrol.setEnabled(false);
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void tbl_kullanicilarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_kullanicilarMouseClicked
        int id = (int) tbl_kullanicilar_model.getValueAt(tbl_kullanicilar.getSelectedRow(), 0);
        Kullanici k = DB_Ders_Icerik_Takibi.searchOgrenciById(id);
        if (k != null) {
            txt_kullanici_id.setText(k.id + "");
            txt_kullanici_id.setEnabled(false);
            txt_guncelleAdSoyad1.setText(k.ad_soyad);
            txt_guncelleAdSoyad1.setEnabled(false);
            txt_guncelleEmail1.setText(k.email);
            txt_guncelleEmail1.setEnabled(false);
            txt_guncelleParola1.setText(k.parola);
            txt_guncelleParola1.setEnabled(false);
            txt_guncelleNumara1.setText(k.ogrenci_numarasi);
            txt_guncelleNumara1.setEnabled(false);
            txt_guncelleKullaniciTuru1.setText(k.kullanici_turu);
            txt_guncelleKullaniciTuru1.setEnabled(false);
            txt_aldigiAkts.setText(k.kullanici_akts + "");
        }
    }//GEN-LAST:event_tbl_kullanicilarMouseClicked

    private void btn_ogrenciAramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ogrenciAramaActionPerformed
        String search = this.txt_ogrenciArama.getText();
        tbl_kullanicilar_model.setRowCount(0);
        ArrayList<Kullanici> kulList = DB_Ders_Icerik_Takibi.aramaTumOgrenci(search);
        for (Kullanici k1 : kulList) {
            if (k1.kullanici_turu.equals("OGRENCI")) {
                tbl_kullanicilar_model.addRow(new Object[]{k1.id, k1.ad_soyad, k1.kullanici_turu, k1.kullanici_akts});
            }
        }
    }//GEN-LAST:event_btn_ogrenciAramaActionPerformed

    private void btn_kullaniciSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kullaniciSilActionPerformed
        if (tbl_kullanicilar.getSelectedRow() < 0) {
            return;
        }
        int id = Integer.parseInt(tbl_kullanicilar_model.getValueAt(tbl_kullanicilar.getSelectedRow(), 0).toString());
        int id_ogrenci = Integer.parseInt(tbl_kullanicilar_model.getValueAt(tbl_kullanicilar.getSelectedRow(), 0).toString());
        if (DB_Ders_Icerik_Takibi.DeleteOgrenciByIdDB(id) && DB_Ders_Icerik_Takibi.DeleteOgrenciById(id_ogrenci)) {
            JOptionPane.showMessageDialog(parentFrame, "Basarili");
        } else {
            JOptionPane.showMessageDialog(parentFrame, "Basarisiz");
        }
    }//GEN-LAST:event_btn_kullaniciSilActionPerformed

    private void btn_bilgileriGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bilgileriGuncelleActionPerformed
        Kullanici k1 = new Kullanici();
        if (kullanici != null) {
            k1.id = Integer.parseInt(txt_akademisyenId.getText());
            txt_akademisyenId.setEnabled(false);
            k1.ad_soyad = txt_guncelleAdSoyad.getText();
            k1.email = txt_guncelleEmail.getText();
            k1.parola = txt_guncelleParola.getText();
            if (DB_Ders_Icerik_Takibi.UpdateKullanici(k1)) {
                JOptionPane.showMessageDialog(parentFrame, "Basarili");
            } else {
                JOptionPane.showMessageDialog(parentFrame, "Basarisiz");
            }
        }
    }//GEN-LAST:event_btn_bilgileriGuncelleActionPerformed

    private void tbl_dersler2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dersler2MouseClicked
        if (tbl_dersler2.getSelectedRow() < 0) {
            return;
        }
        cmbx_haftaSec.setEnabled(true);
        secimiTemizle();
        int ders_id = (int) tbl_dersler_model2.getValueAt(tbl_dersler2.getSelectedRow(), 0);
        btn_icerigiKaydet.setEnabled(true);
        Ders d = DB_Ders_Icerik_Takibi.searchDersById(ders_id);
        if (d != null) {
            lbl_seciliDers.setText(d.ders_adi);
        }
        btn_icerigiKaydet.setEnabled(false);
        btn_icerikGuncelle.setEnabled(false);
        btn_kontrol.setEnabled(false);
        btn_temizle.setEnabled(false);

    }//GEN-LAST:event_tbl_dersler2MouseClicked

    public void secimiTemizle() {
        buttonGroup2.clearSelection();
        rbtn_odev.setSelected(false);
        rbtn_pdf.setSelected(false);
        rbtn_quiz.setSelected(false);
        rbtn_video.setSelected(false);
    }
    private void btn_tumDersArama2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tumDersArama2ActionPerformed
        String search = this.txt_tumDersArama2.getText();
        tbl_dersler_model2.setRowCount(0);
        ArrayList<Ders> dersList = DB_Ders_Icerik_Takibi.aramaTumDers(search);
        for (Ders d1 : dersList) {
            tbl_dersler_model2.addRow(new Object[]{d1.id, d1.ders_adi});
        }
    }//GEN-LAST:event_btn_tumDersArama2ActionPerformed

    private void cmbx_haftaSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbx_haftaSecActionPerformed
        int hafta = cmbx_haftaSec.getSelectedIndex();
        int ders_id = (int) tbl_dersler_model2.getValueAt(tbl_dersler2.getSelectedRow(), 0);
        if (hafta == 0) {
            DuyuruDisiniKapa(false);
            lbl_seciliHafta.setText("Lutfen Hafta Secin");
            btn_icerigiKaydet.setEnabled(false);
            btn_icerikGuncelle.setEnabled(false);
            btn_secimiTemizle.setEnabled(false);
        } else {
            lbl_seciliHafta.setText(hafta + "");
        }
        btn_kontrol.setEnabled(true);
    }//GEN-LAST:event_cmbx_haftaSecActionPerformed

    private void btn_icerigiKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_icerigiKaydetActionPerformed
        Icerik icerik = new Icerik();
        int id_ders = Integer.parseInt(tbl_dersler_model2.getValueAt(tbl_dersler2.getSelectedRow(), 0).toString());
        icerik.ders_id = id_ders;
        icerik.haftasi = cmbx_haftaSec.getSelectedIndex();
        if (rbtn_final.isSelected()) {
            icerik.eklenen = rbtn_final.getText();
        } else if (rbtn_vize.isSelected()) {
            icerik.eklenen = rbtn_vize.getText();
        }
        if (rbtn_quiz.isSelected()) {
            icerik.eklenen += "\n" + rbtn_quiz.getText();
        }
        if (rbtn_odev.isSelected()) {
            icerik.eklenen += "\n" + rbtn_odev.getText();
        }
        if (rbtn_pdf.isSelected()) {
            icerik.eklenen += "\n" + rbtn_pdf.getText();
        }
        if (rbtn_video.isSelected()) {
            icerik.eklenen += "\n" + rbtn_video.getText();
        }
        if (DB_Ders_Icerik_Takibi.AddIcerikToStudentById(icerik.ders_id, icerik.haftasi, icerik.eklenen)) {
            JOptionPane.showMessageDialog(parentFrame, "Basarili");
        } else {
            JOptionPane.showMessageDialog(parentFrame, "Basarisiz");
        }
    }//GEN-LAST:event_btn_icerigiKaydetActionPerformed

    private void btn_secimiTemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_secimiTemizleActionPerformed
        secimiTemizle();
    }//GEN-LAST:event_btn_secimiTemizleActionPerformed

    private void rbtn_finalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_finalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_finalActionPerformed

    private void btn_kontrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kontrolActionPerformed
        int ders_id = (int) tbl_dersler_model2.getValueAt(tbl_dersler2.getSelectedRow(), 0);
        int hafta = cmbx_haftaSec.getSelectedIndex();
        btn_secimiTemizle.setEnabled(true);
        DuyuruDisiniKapa(true);
        if (hafta != 0 && DB_Ders_Icerik_Takibi.IcerikVarMi(ders_id, hafta)) {
            btn_icerigiKaydet.setEnabled(false);
            btn_icerikGuncelle.setEnabled(true);
        } else if (hafta != 0 && !DB_Ders_Icerik_Takibi.IcerikVarMi(ders_id, hafta)) {
            btn_icerigiKaydet.setEnabled(true);
            btn_icerikGuncelle.setEnabled(false);
        } else {
            btn_icerigiKaydet.setEnabled(false);
            btn_icerikGuncelle.setEnabled(false);
        }
    }//GEN-LAST:event_btn_kontrolActionPerformed

    private void btn_icerikGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_icerikGuncelleActionPerformed
        Icerik i = new Icerik();
        int ders_id = (int) tbl_dersler_model2.getValueAt(tbl_dersler2.getSelectedRow(), 0);
        int hafta = cmbx_haftaSec.getSelectedIndex();
        i.ders_id = ders_id;
        i.haftasi = hafta;
        if (DB_Ders_Icerik_Takibi.IcerikVarMi(ders_id, hafta)) {
            if (rbtn_final.isSelected()) {
                i.eklenen = rbtn_final.getText();
            } else if (rbtn_vize.isSelected()) {
                i.eklenen = rbtn_vize.getText();
            }
            if (i.eklenen == null) {
                i.eklenen = "";
            }
            if (rbtn_quiz.isSelected()) {
                i.eklenen += "\n" + rbtn_quiz.getText();
            }
            if (rbtn_odev.isSelected()) {
                i.eklenen += "\n" + rbtn_odev.getText();
            }
            if (rbtn_pdf.isSelected()) {
                i.eklenen += "\n" + rbtn_pdf.getText();
            }
            if (rbtn_video.isSelected()) {
                i.eklenen += "\n" + rbtn_video.getText();
            }
            if (DB_Ders_Icerik_Takibi.UpdateIcerik(i)) {
                JOptionPane.showMessageDialog(parentFrame, "Basarili");
            } else {
                JOptionPane.showMessageDialog(parentFrame, "Basarisiz");
            }
        }
    }//GEN-LAST:event_btn_icerikGuncelleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AkademisyenDersIcerik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AkademisyenDersIcerik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AkademisyenDersIcerik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AkademisyenDersIcerik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Kullanici kullanici = new Kullanici();
                new AkademisyenDersIcerik(kullanici).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bilgileriGuncelle;
    private javax.swing.JButton btn_bilgileriGuncelle1;
    private javax.swing.JButton btn_dersiGuncelle;
    private javax.swing.JButton btn_dersiSil;
    private javax.swing.JButton btn_derstenCikar;
    private javax.swing.JButton btn_icerigiKaydet;
    private javax.swing.JButton btn_icerikGuncelle;
    private javax.swing.JButton btn_kontrol;
    private javax.swing.JButton btn_kullaniciSil;
    private javax.swing.JButton btn_ogrenciArama;
    private javax.swing.JButton btn_secimiTemizle;
    private javax.swing.JButton btn_temizle;
    private javax.swing.JButton btn_tumDersArama;
    private javax.swing.JButton btn_tumDersArama2;
    private javax.swing.JButton btn_yeniDersEkle;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmbx_haftaSec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_ogrenciNumarasi;
    private javax.swing.JLabel lbl_seciliDers;
    private javax.swing.JLabel lbl_seciliHafta;
    private javax.swing.JMenuItem menuItem_cikis;
    private javax.swing.JMenu menu_kullanici;
    private javax.swing.JRadioButton rbtn_final;
    private javax.swing.JRadioButton rbtn_odev;
    private javax.swing.JRadioButton rbtn_pdf;
    private javax.swing.JRadioButton rbtn_quiz;
    private javax.swing.JRadioButton rbtn_video;
    private javax.swing.JRadioButton rbtn_vize;
    private javax.swing.JTable tbl_dersiAlanlar;
    private javax.swing.JTable tbl_dersler;
    private javax.swing.JTable tbl_dersler2;
    private javax.swing.JTable tbl_kullanicilar;
    private javax.swing.JTextField txt_akademisyenId;
    private javax.swing.JTextField txt_aktsGuncelle;
    private javax.swing.JTextField txt_aldigiAkts;
    private javax.swing.JTextField txt_dersAdi;
    private javax.swing.JTextField txt_dersId;
    private javax.swing.JTextField txt_guncelleAdSoyad;
    private javax.swing.JTextField txt_guncelleAdSoyad1;
    private javax.swing.JTextField txt_guncelleEmail;
    private javax.swing.JTextField txt_guncelleEmail1;
    private javax.swing.JTextField txt_guncelleKullaniciTuru1;
    private javax.swing.JTextField txt_guncelleNumara1;
    private javax.swing.JTextField txt_guncelleParola;
    private javax.swing.JTextField txt_guncelleParola1;
    private javax.swing.JTextField txt_kullanici_id;
    private javax.swing.JTextField txt_ogrenciArama;
    private javax.swing.JTextField txt_ogrenciBul;
    private javax.swing.JTextField txt_tumDersArama;
    private javax.swing.JTextField txt_tumDersArama2;
    private javax.swing.JTextArea txta_dersIcerigi;
    // End of variables declaration//GEN-END:variables
}
