/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fsm.alienes_gurel_2121221032_bp2_p2;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author alien
 */
public class KayitOlOgrenci extends javax.swing.JFrame {

    OgrenciGirisi o = new OgrenciGirisi();
    AkademisyenGirisi a = new AkademisyenGirisi();
    Main main = new Main();
    JFrame parentFrame;

    /**
     * Creates new form KayitOl
     */
    public KayitOlOgrenci() {
        initComponents();
        this.setTitle("REGISTER");
        this.parentFrame = parentFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_kayitOl = new javax.swing.JButton();
        btn_kayitIptal = new javax.swing.JButton();
        txt_kayitAdSoyad = new javax.swing.JTextField();
        txt_kayitEmail = new javax.swing.JTextField();
        lbl_ogrenciNumarasi = new javax.swing.JLabel();
        txt_kayitNumara = new javax.swing.JTextField();
        txt_kayitKullaniciTuru = new javax.swing.JTextField();
        txt_kayitParola = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));

        jPanel1.setBackground(new java.awt.Color(51, 51, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "KAYIT OL", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 410));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 410));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 410));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AD - SOYAD");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 88, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("E-MAIL");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 88, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PAROLA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 69, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("KULLANICI TURU");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        btn_kayitOl.setBackground(new java.awt.Color(51, 51, 0));
        btn_kayitOl.setForeground(new java.awt.Color(255, 255, 255));
        btn_kayitOl.setText("KAYIT OL");
        btn_kayitOl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayitOlActionPerformed(evt);
            }
        });
        jPanel1.add(btn_kayitOl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 300, 50));

        btn_kayitIptal.setBackground(new java.awt.Color(51, 51, 0));
        btn_kayitIptal.setForeground(new java.awt.Color(255, 255, 255));
        btn_kayitIptal.setText("IPTAL");
        btn_kayitIptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayitIptalActionPerformed(evt);
            }
        });
        jPanel1.add(btn_kayitIptal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 300, 30));
        jPanel1.add(txt_kayitAdSoyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 150, -1));
        jPanel1.add(txt_kayitEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 150, -1));

        lbl_ogrenciNumarasi.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ogrenciNumarasi.setText("NUMARASI");
        jPanel1.add(lbl_ogrenciNumarasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 120, -1));
        jPanel1.add(txt_kayitNumara, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 150, -1));

        txt_kayitKullaniciTuru.setForeground(new java.awt.Color(0, 0, 0));
        txt_kayitKullaniciTuru.setText("OGRENCI");
        txt_kayitKullaniciTuru.setEnabled(false);
        jPanel1.add(txt_kayitKullaniciTuru, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 150, -1));
        jPanel1.add(txt_kayitParola, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 150, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kayitIptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayitIptalActionPerformed
        o.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_kayitIptalActionPerformed

    private void btn_kayitOlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayitOlActionPerformed
        Kullanici newk = new Kullanici();
        newk.email = txt_kayitEmail.getText();
        newk.ad_soyad = txt_kayitAdSoyad.getText();
        newk.parola = txt_kayitParola.getText();
        newk.kullanici_turu = txt_kayitKullaniciTuru.getText();
        newk.ogrenci_numarasi = txt_kayitNumara.getText();
        if (kayit_icin_uygunMu() == true) {
            if (DB_Ders_Icerik_Takibi.AddPerson(newk)) {
                JOptionPane.showMessageDialog(parentFrame, "Basarili");
            } else {
                JOptionPane.showMessageDialog(parentFrame, "Basarisiz");
            }
        }
    }//GEN-LAST:event_btn_kayitOlActionPerformed

    public boolean kayit_icin_uygunMu() {//regex 
        Kullanici newk = new Kullanici();
        newk.email = txt_kayitEmail.getText();
        newk.ad_soyad = txt_kayitAdSoyad.getText();
        newk.parola = txt_kayitParola.getText();
        newk.ogrenci_numarasi = txt_kayitNumara.getText();

        try {
            if (!newk.ad_soyad.matches("^[a-zA-Z]{3,12}$")) {
                throw new Exception("Lütfen geçerli bir kullanici adi giriniz!\nKullanici adiniz en az 3 en fazla 12 karakter olabilir!\nBuyuk ve kucuk harf kullanmalisiniz!\nOrnek: Example");
            }
            if (txt_kayitAdSoyad.getText().isEmpty()) {
                throw new Exception("Lütfen kullanıcı adınızı giriniz!");
            }
            if (!newk.email.matches("^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])[a-zA-Z\\d]{6,}@(gmail)\\.com$")) {
                throw new Exception("Lütfen geçerli bir e-mail adresi giriniz!\nE-mail adresiniz en az 6 karakter uzunlugunda olmalidir!\nEn az bir tane rakam ve buyuk kucuk harf icermelidir!\nYalnizca @gmail.com ile giris yapabilirsiniz!\nornek: Example123@gmail.com");
            }
            if (txt_kayitEmail.getText().isEmpty()) {
                throw new Exception("Lütfen email adresinizi giriniz!");
            }
            if (!newk.parola.matches("\\w{4,}")) {
                throw new Exception("Lütfen şifrenizin uzunluğu en az 4 karakter olacak sekilde giriniz!");
            }
            if (!newk.ogrenci_numarasi.matches("^21212210\\d{2}$")) {
                throw new Exception("Lütfen geçerli bir ogrenci numarasi giriniz\nOgrenci numaraniz 21212210 ile baslayip 10 haneli olmalidir!\nOrnek: 2121221032");
            }
            Kullanici k1 = new Kullanici();
            k1.parola = txt_kayitParola.getText();
            String rpassword = JOptionPane.showInputDialog(rootPane, "Lütfen parolanızı tekrar giriniz.", JOptionPane.INFORMATION_MESSAGE);
            if (k1.parola.equals(rpassword)) {
                return true;
            } else if (!k1.parola.equals(rpassword)) {
                throw new Exception("Parolanız önceki ile eşleşmiyor.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Exception", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KayitOlOgrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KayitOlOgrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KayitOlOgrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KayitOlOgrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KayitOlOgrenci().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kayitIptal;
    private javax.swing.JButton btn_kayitOl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_ogrenciNumarasi;
    private javax.swing.JTextField txt_kayitAdSoyad;
    private javax.swing.JTextField txt_kayitEmail;
    private javax.swing.JTextField txt_kayitKullaniciTuru;
    private javax.swing.JTextField txt_kayitNumara;
    private javax.swing.JTextField txt_kayitParola;
    // End of variables declaration//GEN-END:variables
}
