/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fsm.alienes_gurel_2121221032_bp2_p2;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author alien
 */
public class KayitOlAkademisyen extends javax.swing.JFrame {

    JFrame parentFrame;
    OgrenciGirisi o = new OgrenciGirisi();
    AkademisyenGirisi a = new AkademisyenGirisi();
    Main main = new Main();

    /**
     * Creates new form KayitOl
     */
    public KayitOlAkademisyen() {
        initComponents();
        this.setTitle("REGISTER");
        this.parentFrame = parentFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_kayitOl = new javax.swing.JButton();
        btn_kayitIptal = new javax.swing.JButton();
        txt_kayitAdSoyad = new javax.swing.JTextField();
        txt_kayitEmail = new javax.swing.JTextField();
        txt_kayitKullaniciTuru = new javax.swing.JTextField();
        txt_registerParola = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));

        jPanel1.setBackground(new java.awt.Color(51, 51, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "KAYIT OL", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 410));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 410));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 410));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AD - SOYAD");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("E-MAIL");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PAROLA");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("KULLANICI TURU");

        btn_kayitOl.setBackground(new java.awt.Color(51, 51, 0));
        btn_kayitOl.setForeground(new java.awt.Color(255, 255, 255));
        btn_kayitOl.setText("KAYIT OL");
        btn_kayitOl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayitOlActionPerformed(evt);
            }
        });

        btn_kayitIptal.setBackground(new java.awt.Color(51, 51, 0));
        btn_kayitIptal.setForeground(new java.awt.Color(255, 255, 255));
        btn_kayitIptal.setText("IPTAL");
        btn_kayitIptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayitIptalActionPerformed(evt);
            }
        });

        txt_kayitKullaniciTuru.setForeground(new java.awt.Color(0, 0, 0));
        txt_kayitKullaniciTuru.setText("AKADEMISYEN");
        txt_kayitKullaniciTuru.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(txt_kayitAdSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(txt_kayitEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_kayitOl, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_kayitIptal, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_kayitKullaniciTuru, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txt_registerParola)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kayitAdSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kayitEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_registerParola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kayitKullaniciTuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(btn_kayitOl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_kayitIptal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kayitIptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayitIptalActionPerformed
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_kayitIptalActionPerformed

    private void btn_kayitOlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayitOlActionPerformed
        Kullanici newk = new Kullanici();
        newk.email = txt_kayitEmail.getText();
        newk.ad_soyad = txt_kayitAdSoyad.getText();
        newk.parola = txt_registerParola.getText();
        newk.kullanici_turu = txt_kayitKullaniciTuru.getText();
        newk.ogrenci_numarasi = "";
        if (kayit_icin_uygunMu() == true) {
            if (DB_Ders_Icerik_Takibi.AddPersonAkademisyen(newk)) {
                JOptionPane.showMessageDialog(parentFrame, "Basarili");
            } else {
                JOptionPane.showMessageDialog(parentFrame, "Basarisiz");
            }
        }
    }//GEN-LAST:event_btn_kayitOlActionPerformed

    public boolean kayit_icin_uygunMu() {//regex
        Kullanici newk = new Kullanici();
        newk.email = txt_kayitEmail.getText();
        newk.ad_soyad = txt_kayitAdSoyad.getText();
        newk.parola = txt_registerParola.getText();

        try {
            if (!newk.ad_soyad.matches("^[a-zA-Z]{3,12}$")) {
                throw new Exception("Lütfen geçerli bir kullanici adi giriniz!\nKullanici adiniz en az 3 en fazla 12 karakter olabilir!\nBuyuk ve kucuk harf kullanmalisiniz!\nOrnek: Example");
            }
            if (txt_kayitAdSoyad.getText().isEmpty()) {
                throw new Exception("Lütfen kullanıcı adınızı giriniz!");
            }
            if (!newk.email.matches("^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])[a-zA-Z\\d]{6,}@(gmail)\\.com$")) {
                throw new Exception("Lütfen geçerli bir e-mail adresi giriniz!\nE-mail adresiniz en az 6 karakter uzunlugunda olmalidir!\nEn az bir tane rakam ve buyuk kucuk harf icermelidir!\nYalnizca @gmail.com ile giris yapabilirsiniz!\nornek: Example123@gmail.com");
            }
            if (txt_kayitEmail.getText().isEmpty()) {
                throw new Exception("Lütfen email adresinizi giriniz!");
            }
            if (!newk.parola.matches("\\w{4,}")) {
                throw new Exception("Lütfen şifrenizin uzunluğu en az 4 karakter olacak sekilde giriniz!");
            }
            Kullanici k1 = new Kullanici();
            k1.parola = txt_registerParola.getText();
            String rpassword = JOptionPane.showInputDialog(rootPane, "Lütfen parolanızı tekrar giriniz.", JOptionPane.INFORMATION_MESSAGE);
            if (k1.parola.equals(rpassword)) {
                return true;
            } else if (!k1.parola.equals(rpassword)) {
                throw new Exception("Parolanız önceki ile eşleşmiyor.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Exception", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KayitOlAkademisyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KayitOlAkademisyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KayitOlAkademisyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KayitOlAkademisyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KayitOlAkademisyen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kayitIptal;
    private javax.swing.JButton btn_kayitOl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_kayitAdSoyad;
    private javax.swing.JTextField txt_kayitEmail;
    private javax.swing.JTextField txt_kayitKullaniciTuru;
    private javax.swing.JTextField txt_registerParola;
    // End of variables declaration//GEN-END:variables
}
