/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fsm.alienes_gurel_2121221032_bp2_p2;

/**
 *
 * @author alien
 */
public class Main extends javax.swing.JFrame {


    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setTitle("DERS ICERIK TAKIBI");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lbl_main = new javax.swing.JPanel();
        btn_akademisyenGirisi = new javax.swing.JButton();
        btn_ogrenciGirisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(450, 350));
        setMinimumSize(new java.awt.Dimension(450, 350));
        setPreferredSize(new java.awt.Dimension(450, 350));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        lbl_main.setBackground(new java.awt.Color(51, 0, 0));
        lbl_main.setLayout(new java.awt.GridBagLayout());

        btn_akademisyenGirisi.setBackground(new java.awt.Color(51, 0, 0));
        btn_akademisyenGirisi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_akademisyenGirisi.setForeground(new java.awt.Color(255, 255, 255));
        btn_akademisyenGirisi.setText("AKADEMISYEN GIRISI");
        btn_akademisyenGirisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_akademisyenGirisiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 90, 118, 76);
        lbl_main.add(btn_akademisyenGirisi, gridBagConstraints);

        btn_ogrenciGirisi.setBackground(new java.awt.Color(51, 0, 0));
        btn_ogrenciGirisi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_ogrenciGirisi.setForeground(new java.awt.Color(255, 255, 255));
        btn_ogrenciGirisi.setText("OGRENCI GIRISI");
        btn_ogrenciGirisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ogrenciGirisiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 46;
        gridBagConstraints.ipady = 43;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(90, 90, 0, 0);
        lbl_main.add(btn_ogrenciGirisi, gridBagConstraints);

        getContentPane().add(lbl_main);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ogrenciGirisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ogrenciGirisiActionPerformed
        OgrenciGirisi ogrenciGirisi = new OgrenciGirisi();
        ogrenciGirisi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ogrenciGirisiActionPerformed

    private void btn_akademisyenGirisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_akademisyenGirisiActionPerformed
        AkademisyenGirisi akademisyenGirisi = new AkademisyenGirisi();
        akademisyenGirisi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_akademisyenGirisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_akademisyenGirisi;
    private javax.swing.JButton btn_ogrenciGirisi;
    private javax.swing.JPanel lbl_main;
    // End of variables declaration//GEN-END:variables
}
