/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fsm.alienes_gurel_2121221032_bp2_p2;

import java.awt.List;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alien
 */
public class OgrenciDersIcerik extends javax.swing.JFrame {

    JFrame parentFrame;
    Main main = new Main();
    Kullanici kullanici;
    DefaultTableModel tbl_dersler_model;
    DefaultTableModel tbl_ogrencıAldıgıDersler_model;

    /**
     * Creates new form OgrenciDersIcerik
     */
    public OgrenciDersIcerik(Kullanici kullanici) {
        initComponents();
        this.setTitle("OGRENCI");
        this.kullanici = kullanici;
        menu_kullanici.setText(kullanici.ad_soyad);
        lbl_toplamAkts.setText(kullanici.kullanici_akts + "");
        tbl_dersler_model = new DefaultTableModel();
        tbl_dersler_model.setColumnIdentifiers(new Object[]{"ID", "DERS ADI", "DERS AKTS"});
        tbl_tumDersler.setModel(tbl_dersler_model);
        tbl_ogrencıAldıgıDersler_model = new DefaultTableModel();
        tbl_ogrencıAldıgıDersler_model.setColumnIdentifiers(new Object[]{"ID", "DERS ADI", "DERS AKTS"});
        tbl_ogrencıAldıgıDersler.setModel(tbl_ogrencıAldıgıDersler_model);
        temizle();
        SetCourseToTable();
        OgrenciSetCourseToTable();
        guncelle();
        txt_dersId.setEnabled(false);
        txt_dersAdi.setEnabled(false);
        txt_dersAkts.setEnabled(false);
        txta_dersIcerigi.setEnabled(false);
    }

    private void SetCourseToTable() {
        ArrayList<Ders> dersler = DB_Ders_Icerik_Takibi.DersleriGetir();
        tbl_dersler_model.setRowCount(0);
        for (Ders ders : dersler) {
            tbl_dersler_model.addRow(new Object[]{ders.id, ders.ders_adi, ders.ders_akts});
        }
    }

    private void OgrenciSetCourseToTable() {

        txt_ogrencıDersArama.setText(kullanici.id + "");
        txt_ogrencıDersArama.setEnabled(false);
        int search = kullanici.id;
        ArrayList<Ders> dersler = DB_Ders_Icerik_Takibi.aramaOgrenciDers(search);
        tbl_ogrencıAldıgıDersler_model.setRowCount(0);
        for (Ders ders : dersler) {
            tbl_ogrencıAldıgıDersler_model.addRow(new Object[]{ders.id, ders.ders_adi, ders.ders_akts});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_dersId = new javax.swing.JTextField();
        txt_dersAdi = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txta_dersIcerigi = new javax.swing.JTextArea();
        btn_derseKatil = new javax.swing.JButton();
        btn_derstenCik = new javax.swing.JButton();
        btn_iptal = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_dersAkts = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tumDersler = new javax.swing.JTable();
        txt_tumDersArama = new javax.swing.JTextField();
        btn_tumDersArama = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txt_ogrencıDersArama = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_ogrencıAldıgıDersler = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_toplamAkts = new javax.swing.JLabel();
        lbl_kalan_akts = new javax.swing.JLabel();
        btn_guncelle = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        cmbx_derslerim = new javax.swing.JComboBox<>();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_1 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_2 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txt_3 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txt_4 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        txt_5 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        txt_6 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        txt_7 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        txt_8 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        txt_9 = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        txt_10 = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        txt_11 = new javax.swing.JTextArea();
        jScrollPane15 = new javax.swing.JScrollPane();
        txt_12 = new javax.swing.JTextArea();
        jScrollPane16 = new javax.swing.JScrollPane();
        txt_13 = new javax.swing.JTextArea();
        jScrollPane17 = new javax.swing.JScrollPane();
        txt_14 = new javax.swing.JTextArea();
        jScrollPane18 = new javax.swing.JScrollPane();
        txt_15 = new javax.swing.JTextArea();
        btn_sayfayiGuncelle = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_ogrenciId = new javax.swing.JTextField();
        txt_guncelleAdSoyad = new javax.swing.JTextField();
        txt_guncelleEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_guncelleParola = new javax.swing.JTextField();
        txt_guncelleNumara = new javax.swing.JTextField();
        lbl_ogrenciNumarasi = new javax.swing.JLabel();
        btn_bilgileriGuncelle = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt_akts = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_kullanici = new javax.swing.JMenu();
        menuItem_cikis = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 715));
        setMinimumSize(new java.awt.Dimension(1000, 715));
        setPreferredSize(new java.awt.Dimension(1000, 715));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(850, 550));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DERS BILGILERI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DERS ADI");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DERS ID");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DERS BILGISI");

        txta_dersIcerigi.setColumns(20);
        txta_dersIcerigi.setRows(5);
        jScrollPane3.setViewportView(txta_dersIcerigi);

        btn_derseKatil.setText("DERSE KATIL");
        btn_derseKatil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_derseKatilActionPerformed(evt);
            }
        });

        btn_derstenCik.setText("DERSTEN CIK");
        btn_derstenCik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_derstenCikActionPerformed(evt);
            }
        });

        btn_iptal.setText("IPTAL");
        btn_iptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iptalActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DERS AKTS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_derseKatil, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_derstenCik, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3)
                    .addComponent(btn_iptal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_dersId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_dersAdi, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txt_dersAkts))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_dersId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_dersAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txt_dersAkts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_derseKatil, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_derstenCik, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_iptal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 320, 530));

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TUM DERSLER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        tbl_tumDersler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DERS ADI", "DERS AKTS"
            }
        ));
        tbl_tumDersler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_tumDerslerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_tumDersler);

        btn_tumDersArama.setText("DERS ARAMA");
        btn_tumDersArama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tumDersAramaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txt_tumDersArama)
                        .addGap(18, 18, 18)
                        .addComponent(btn_tumDersArama, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tumDersArama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tumDersArama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 540, 290));

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OGRENCI ALDIGI DERSLER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(txt_ogrencıDersArama, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 17, 105, -1));

        tbl_ogrencıAldıgıDersler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DERS ADI", "DERS AKTS"
            }
        ));
        tbl_ogrencıAldıgıDersler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ogrencıAldıgıDerslerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_ogrencıAldıgıDersler);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 45, 520, 190));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("KALAN AKTS :");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 20, 77, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TOPLAM AKTS :");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 20, -1, -1));

        lbl_toplamAkts.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(lbl_toplamAkts, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 17, 43, 22));

        lbl_kalan_akts.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(lbl_kalan_akts, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 17, 43, 22));

        btn_guncelle.setText("GUNCELLE");
        btn_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guncelleActionPerformed(evt);
            }
        });
        jPanel5.add(btn_guncelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 17, 104, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 540, 240));

        jTabbedPane1.addTab("DERS ISLEMLERI", jPanel2);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jPanel8.setBackground(new java.awt.Color(51, 0, 0));
        jPanel8.setMinimumSize(new java.awt.Dimension(1000, 715));
        jPanel8.setPreferredSize(new java.awt.Dimension(1000, 715));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbx_derslerim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbx_derslerimMouseClicked(evt);
            }
        });
        jPanel8.add(cmbx_derslerim, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 40));

        jLabel45.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("HAFTA 1");
        jPanel8.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jLabel46.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("HAFTA 2");
        jPanel8.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        jLabel47.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("HAFTA 3");
        jPanel8.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, -1));

        jLabel48.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("HAFTA 4");
        jPanel8.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        jLabel49.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("HAFTA 5");
        jPanel8.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, -1, 20));

        jLabel50.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("HAFTA 15");
        jPanel8.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 530, -1, -1));

        jLabel51.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("HAFTA 13");
        jPanel8.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, -1, -1));

        jLabel52.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("HAFTA 6");
        jPanel8.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        jLabel53.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("HAFTA 7");
        jPanel8.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, 20));

        jLabel54.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("HAFTA 8");
        jPanel8.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        jLabel55.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("HAFTA 9");
        jPanel8.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, -1, -1));

        jLabel56.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("HAFTA 10");
        jPanel8.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, -1, -1));

        jLabel57.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("HAFTA 14");
        jPanel8.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, -1, -1));

        jLabel58.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("HAFTA 11");
        jPanel8.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, -1, -1));

        jLabel59.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("HAFTA 12");
        jPanel8.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, -1, -1));

        txt_1.setColumns(20);
        txt_1.setRows(5);
        jScrollPane4.setViewportView(txt_1);

        jPanel8.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        txt_2.setColumns(20);
        txt_2.setRows(5);
        jScrollPane5.setViewportView(txt_2);

        jPanel8.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        txt_3.setColumns(20);
        txt_3.setRows(5);
        jScrollPane6.setViewportView(txt_3);

        jPanel8.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, -1, -1));

        txt_4.setColumns(20);
        txt_4.setRows(5);
        jScrollPane7.setViewportView(txt_4);

        jPanel8.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, -1, -1));

        txt_5.setColumns(20);
        txt_5.setRows(5);
        jScrollPane8.setViewportView(txt_5);

        jPanel8.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, -1, -1));

        txt_6.setColumns(20);
        txt_6.setRows(5);
        jScrollPane9.setViewportView(txt_6);

        jPanel8.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        txt_7.setColumns(20);
        txt_7.setRows(5);
        jScrollPane10.setViewportView(txt_7);

        jPanel8.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, -1));

        txt_8.setColumns(20);
        txt_8.setRows(5);
        jScrollPane11.setViewportView(txt_8);

        jPanel8.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, -1));

        txt_9.setColumns(20);
        txt_9.setRows(5);
        jScrollPane12.setViewportView(txt_9);

        jPanel8.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, -1));

        txt_10.setColumns(20);
        txt_10.setRows(5);
        jScrollPane13.setViewportView(txt_10);

        jPanel8.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, -1, -1));

        txt_11.setColumns(20);
        txt_11.setRows(5);
        jScrollPane14.setViewportView(txt_11);

        jPanel8.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, -1, -1));

        txt_12.setColumns(20);
        txt_12.setRows(5);
        jScrollPane15.setViewportView(txt_12);

        jPanel8.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, -1, -1));

        txt_13.setColumns(20);
        txt_13.setRows(5);
        jScrollPane16.setViewportView(txt_13);

        jPanel8.add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, -1, -1));

        txt_14.setColumns(20);
        txt_14.setRows(5);
        jScrollPane17.setViewportView(txt_14);

        jPanel8.add(jScrollPane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, -1, -1));

        txt_15.setColumns(20);
        txt_15.setRows(5);
        jScrollPane18.setViewportView(txt_15);

        jPanel8.add(jScrollPane18, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 550, -1, -1));

        btn_sayfayiGuncelle.setText("SAYFAYI GUNCELLE");
        btn_sayfayiGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sayfayiGuncelleActionPerformed(evt);
            }
        });
        jPanel8.add(btn_sayfayiGuncelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 2, 210, 40));

        jPanel7.add(jPanel8);

        jTabbedPane1.addTab("DERSIN ICERIGI", jPanel7);

        jPanel1.setBackground(new java.awt.Color(51, 51, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OGRENCI BILGILERIMI GUNCELLE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel6.setBackground(new java.awt.Color(0, 51, 51));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("OGRENCI ID");

        txt_ogrenciId.setEnabled(false);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("AD - SOYAD");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("E-MAIL");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PAROLA");

        lbl_ogrenciNumarasi.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ogrenciNumarasi.setText("OGRENCI NUMARASI");

        btn_bilgileriGuncelle.setBackground(new java.awt.Color(51, 51, 0));
        btn_bilgileriGuncelle.setForeground(new java.awt.Color(255, 255, 255));
        btn_bilgileriGuncelle.setText("BILGILERIMI GUNCELLE");
        btn_bilgileriGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bilgileriGuncelleActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("TOPLAM AKTS");

        txt_akts.setEnabled(false);
        txt_akts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_aktsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_guncelleAdSoyad)
                                    .addComponent(txt_ogrenciId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_ogrenciNumarasi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_akts, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txt_guncelleNumara)
                                    .addComponent(txt_guncelleEmail)
                                    .addComponent(txt_guncelleParola, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_bilgileriGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_ogrenciId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_guncelleAdSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_guncelleEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_guncelleParola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_guncelleNumara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ogrenciNumarasi))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_akts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btn_bilgileriGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new java.awt.GridBagConstraints());

        jTabbedPane1.addTab("OGRENCI BILGILERINI GUNCELLE", jPanel1);

        getContentPane().add(jTabbedPane1);

        menu_kullanici.setText("KULLANICI");

        menuItem_cikis.setText("CIKIS YAP");
        menuItem_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_cikisActionPerformed(evt);
            }
        });
        menu_kullanici.add(menuItem_cikis);

        jMenuBar1.add(menu_kullanici);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_derseKatilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_derseKatilActionPerformed
        if (tbl_tumDersler.getSelectedRow() < 0) {
            return;
        }
        int id_ders = Integer.parseInt(tbl_dersler_model.getValueAt(tbl_tumDersler.getSelectedRow(), 0).toString());
        String ders_adi = tbl_dersler_model.getValueAt(tbl_tumDersler.getSelectedRow(), 1).toString();
        int ders_akts = Integer.parseInt(tbl_dersler_model.getValueAt(tbl_tumDersler.getSelectedRow(), 2).toString());
        if (kullanici.kalan_akts >= ders_akts) {
            DB_Ders_Icerik_Takibi.AddCourseToStudentById(this.kullanici.id, id_ders, ders_adi, ders_akts);
            ArrayList<Ders> dersler = DB_Ders_Icerik_Takibi.GetStudentSelectedCoursesByIdJoin(this.kullanici.id);
            tbl_ogrencıAldıgıDersler_model.setRowCount(0);
            for (Ders ders : dersler) {
                tbl_ogrencıAldıgıDersler_model.addRow(new Object[]{ders.id, ders.ders_adi, ders.ders_akts});
            }
            txt_dersId.setText("");
            txt_dersAdi.setText("");
            txta_dersIcerigi.setText("");
            txt_dersAkts.setText("");
            btn_derseKatil.setEnabled(false);
            btn_derstenCik.setEnabled(false);
            guncelle();
        } else {
            JOptionPane.showMessageDialog(parentFrame, "Basarisiz");
        }
    }//GEN-LAST:event_btn_derseKatilActionPerformed

    private void menuItem_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_cikisActionPerformed
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuItem_cikisActionPerformed

    private void btn_derstenCikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_derstenCikActionPerformed
        if (tbl_ogrencıAldıgıDersler.getSelectedRow() < 0) {
            return;
        }
        int id_ders = Integer.parseInt(tbl_ogrencıAldıgıDersler_model.getValueAt(tbl_ogrencıAldıgıDersler.getSelectedRow(), 0).toString());
        DB_Ders_Icerik_Takibi.DeleteCourseToStudentById(this.kullanici.id, id_ders);
        ArrayList<Ders> dersler = DB_Ders_Icerik_Takibi.GetStudentSelectedCoursesByIdJoin(this.kullanici.id);
        tbl_ogrencıAldıgıDersler_model.setRowCount(0);
        for (Ders ders : dersler) {
            tbl_ogrencıAldıgıDersler_model.addRow(new Object[]{ders.id, ders.ders_adi, ders.ders_akts});
        }
        guncelle();
    }//GEN-LAST:event_btn_derstenCikActionPerformed

    private void btn_tumDersAramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tumDersAramaActionPerformed
        String search = this.txt_tumDersArama.getText();
        tbl_dersler_model.setRowCount(0);
        ArrayList<Ders> dersList = DB_Ders_Icerik_Takibi.aramaTumDers(search);
        for (Ders d1 : dersList) {
            tbl_dersler_model.addRow(new Object[]{d1.id, d1.ders_adi, d1.ders_akts});
        }
        txt_dersId.setText("");
        txt_dersAdi.setText("");
        txta_dersIcerigi.setText("");
        txt_dersAkts.setText("");
    }//GEN-LAST:event_btn_tumDersAramaActionPerformed

    private void tbl_tumDerslerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_tumDerslerMouseClicked
        int id = (int) tbl_dersler_model.getValueAt(tbl_tumDersler.getSelectedRow(), 0);
        Ders d = DB_Ders_Icerik_Takibi.searchDersById(id);
        btn_derseKatil.setEnabled(true);
        btn_derstenCik.setEnabled(false);
        if (d != null) {
            txt_dersId.setText(d.id + "");
            txt_dersId.setEnabled(false);
            txt_dersAdi.setText(d.ders_adi);
            txt_dersAdi.setEnabled(false);
            txt_dersAkts.setText(d.ders_akts + "");
            txt_dersAkts.setEnabled(false);
            txta_dersIcerigi.setText(d.icerik);
            txta_dersIcerigi.setEnabled(false);
        }
        Object value = tbl_dersler_model.getValueAt(tbl_tumDersler.getSelectedRow(), 0);
        boolean valueExists = false;
        for (int i = 0; i < tbl_ogrencıAldıgıDersler_model.getRowCount(); i++) {
            Object tableValue = tbl_ogrencıAldıgıDersler_model.getValueAt(i, 0);
            if (value.equals(tableValue)) {
                valueExists = true;
                break;
            }
        }
        if (valueExists) {
            btn_derseKatil.setEnabled(false);
        } else {
            btn_derseKatil.setEnabled(true);
        }
    }//GEN-LAST:event_tbl_tumDerslerMouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        if (kullanici != null) {
            txt_ogrenciId.setText(kullanici.id + "");
            txt_ogrenciId.setEnabled(false);
            txt_guncelleAdSoyad.setText(kullanici.ad_soyad + "");
            txt_guncelleEmail.setText(kullanici.email + "");
            txt_guncelleParola.setText(kullanici.parola + "");
            txt_guncelleNumara.setText(kullanici.ogrenci_numarasi + "");
            txt_akts.setText(kullanici.kullanici_akts + "");
        }
        ArrayList<Object> data = new ArrayList<>();
        for (int i = 0; i < tbl_ogrencıAldıgıDersler.getRowCount(); i++) {
            Object value = tbl_ogrencıAldıgıDersler.getValueAt(i, 1);
            data.add(value);
        }
        cmbx_derslerim.removeAllItems();
        for (Object value : data) {
            cmbx_derslerim.addItem((String) value);
        }

    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void tbl_ogrencıAldıgıDerslerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ogrencıAldıgıDerslerMouseClicked
        btn_derstenCik.setEnabled(true);
        btn_derseKatil.setEnabled(false);
        int id = (int) tbl_ogrencıAldıgıDersler_model.getValueAt(tbl_ogrencıAldıgıDersler.getSelectedRow(), 0);
        Ders d = DB_Ders_Icerik_Takibi.searchDersById(id);
        if (d != null) {
            txt_dersId.setText(d.id + "");
            txt_dersId.setEnabled(false);
            txt_dersAdi.setText(d.ders_adi);
            txt_dersAdi.setEnabled(false);
            txt_dersAkts.setText(d.ders_akts + "");
            txt_dersAkts.setEnabled(false);
            txta_dersIcerigi.setText(d.icerik);
            txta_dersIcerigi.setEnabled(false);
        }
    }//GEN-LAST:event_tbl_ogrencıAldıgıDerslerMouseClicked

    private void btn_bilgileriGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bilgileriGuncelleActionPerformed
        Kullanici k1 = new Kullanici();
        if (kullanici != null) {
            k1.id = Integer.parseInt(txt_ogrenciId.getText());
            txt_ogrenciId.setEnabled(false);
            k1.ad_soyad = txt_guncelleAdSoyad.getText();
            k1.email = txt_guncelleEmail.getText();
            k1.parola = txt_guncelleParola.getText();
            k1.ogrenci_numarasi = txt_guncelleNumara.getText();
            k1.kullanici_akts = Integer.parseInt(txt_akts.getText());
            DB_Ders_Icerik_Takibi.UpdateKullanici(k1);
        }
    }//GEN-LAST:event_btn_bilgileriGuncelleActionPerformed

    private void btn_iptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iptalActionPerformed
        txt_dersId.setText("");
        txt_dersAdi.setText("");
        txta_dersIcerigi.setText("");
        txt_dersAkts.setText("");
    }//GEN-LAST:event_btn_iptalActionPerformed

    private void txt_aktsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_aktsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_aktsActionPerformed

    private void btn_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guncelleActionPerformed
        guncelle();
    }//GEN-LAST:event_btn_guncelleActionPerformed

    private void cmbx_derslerimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbx_derslerimMouseClicked

    }//GEN-LAST:event_cmbx_derslerimMouseClicked

    private void btn_sayfayiGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sayfayiGuncelleActionPerformed
        temizle();
        if (cmbx_derslerim.getSelectedItem() != null) {
            Ders ders = new Ders();
            Icerik icerik = new Icerik();
            String ders_adi = cmbx_derslerim.getSelectedItem().toString();
            if (ders_adi.equals(DB_Ders_Icerik_Takibi.DersiBul(ders_adi).ders_adi)) {
                ders = DB_Ders_Icerik_Takibi.DersiBul(ders_adi);
                icerik = DB_Ders_Icerik_Takibi.IcerikBul(ders.id);
                switch (icerik.haftasi) {
                    case 1:
                        txt_1.setText(icerik.eklenen);
                        break;
                    case 2:
                        txt_2.setText(icerik.eklenen);
                        break;
                    case 3:
                        txt_3.setText(icerik.eklenen);
                        break;
                    case 4:
                        txt_4.setText(icerik.eklenen);
                        break;
                    case 5:
                        txt_5.setText(icerik.eklenen);
                        break;
                    case 6:
                        txt_6.setText(icerik.eklenen);
                        break;
                    case 7:
                        txt_7.setText(icerik.eklenen);
                        break;
                    case 8:
                        txt_8.setText(icerik.eklenen);
                        break;
                    case 9:
                        txt_9.setText(icerik.eklenen);
                        break;
                    case 10:
                        txt_10.setText(icerik.eklenen);
                        break;
                    case 11:
                        txt_11.setText(icerik.eklenen);
                        break;
                    case 12:
                        txt_12.setText(icerik.eklenen);
                        break;
                    case 13:
                        txt_13.setText(icerik.eklenen);
                        break;
                    case 14:
                        txt_14.setText(icerik.eklenen);
                        break;
                    case 15:
                        txt_15.setText(icerik.eklenen);
                        break;
                }
            }
        }
    }//GEN-LAST:event_btn_sayfayiGuncelleActionPerformed
    public void guncelle() {
        int toplam = 0;
        int rowCount = tbl_ogrencıAldıgıDersler_model.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            Object alinan_toplam_akts = tbl_ogrencıAldıgıDersler_model.getValueAt(i, 2);
            toplam += Integer.parseInt(String.valueOf(alinan_toplam_akts));
        }
        int son = kullanici.kullanici_akts - toplam;
        lbl_kalan_akts.setText(String.valueOf(son));
        kullanici.kalan_akts = son;
        DB_Ders_Icerik_Takibi.UpdateAkts(kullanici);
    }

    public void temizle() {
        txt_1.setText("");
        txt_2.setText("");
        txt_3.setText("");
        txt_4.setText("");
        txt_5.setText("");
        txt_6.setText("");
        txt_7.setText("");
        txt_8.setText("");
        txt_9.setText("");
        txt_10.setText("");
        txt_11.setText("");
        txt_12.setText("");
        txt_13.setText("");
        txt_14.setText("");
        txt_15.setText("");
        txt_1.setEnabled(false);
        txt_2.setEnabled(false);
        txt_3.setEnabled(false);
        txt_4.setEnabled(false);
        txt_5.setEnabled(false);
        txt_6.setEnabled(false);
        txt_7.setEnabled(false);
        txt_8.setEnabled(false);
        txt_9.setEnabled(false);
        txt_10.setEnabled(false);
        txt_11.setEnabled(false);
        txt_12.setEnabled(false);
        txt_13.setEnabled(false);
        txt_14.setEnabled(false);
        txt_15.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OgrenciDersIcerik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OgrenciDersIcerik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OgrenciDersIcerik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OgrenciDersIcerik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Kullanici kullanici = new Kullanici();
                new OgrenciDersIcerik(kullanici).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bilgileriGuncelle;
    private javax.swing.JButton btn_derseKatil;
    private javax.swing.JButton btn_derstenCik;
    private javax.swing.JButton btn_guncelle;
    private javax.swing.JButton btn_iptal;
    private javax.swing.JButton btn_sayfayiGuncelle;
    private javax.swing.JButton btn_tumDersArama;
    private javax.swing.JComboBox<String> cmbx_derslerim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_kalan_akts;
    private javax.swing.JLabel lbl_ogrenciNumarasi;
    private javax.swing.JLabel lbl_toplamAkts;
    private javax.swing.JMenuItem menuItem_cikis;
    private javax.swing.JMenu menu_kullanici;
    private javax.swing.JTable tbl_ogrencıAldıgıDersler;
    private javax.swing.JTable tbl_tumDersler;
    private javax.swing.JTextArea txt_1;
    private javax.swing.JTextArea txt_10;
    private javax.swing.JTextArea txt_11;
    private javax.swing.JTextArea txt_12;
    private javax.swing.JTextArea txt_13;
    private javax.swing.JTextArea txt_14;
    private javax.swing.JTextArea txt_15;
    private javax.swing.JTextArea txt_2;
    private javax.swing.JTextArea txt_3;
    private javax.swing.JTextArea txt_4;
    private javax.swing.JTextArea txt_5;
    private javax.swing.JTextArea txt_6;
    private javax.swing.JTextArea txt_7;
    private javax.swing.JTextArea txt_8;
    private javax.swing.JTextArea txt_9;
    private javax.swing.JTextField txt_akts;
    private javax.swing.JTextField txt_dersAdi;
    private javax.swing.JTextField txt_dersAkts;
    private javax.swing.JTextField txt_dersId;
    private javax.swing.JTextField txt_guncelleAdSoyad;
    private javax.swing.JTextField txt_guncelleEmail;
    private javax.swing.JTextField txt_guncelleNumara;
    private javax.swing.JTextField txt_guncelleParola;
    private javax.swing.JTextField txt_ogrenciId;
    private javax.swing.JTextField txt_ogrencıDersArama;
    private javax.swing.JTextField txt_tumDersArama;
    private javax.swing.JTextArea txta_dersIcerigi;
    // End of variables declaration//GEN-END:variables
}
